// <auto-generated />
using System;
using BudgetingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318221251_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetingApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Supermarkets, grocery stores, bulk food, and online grocery delivery",
                            Keywords = "grocery,supermarket,food store,produce,organic,market,bulk,loblaws,metro,sobeys,freshco,food basics,t&t,farm boy,whole foods,longos,safeway,save on foods,maxi,provigo,instacart,goodfood,hellofresh,costco",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Restaurants, cafes, coffee shops, fast food, bars, and food delivery apps",
                            Keywords = "restaurant,cafe,coffee,takeout,delivery,fast food,pizza,sushi,bistro,bar,pub,diner,grill,doordash,uber eats,skip the dishes,tim hortons,starbucks,mcdonalds,subway,burger king,wendy's,harveys,a&w,pizza pizza,dominos,taco bell,kfc,chipotle,booster juice,freshii,dairy queen",
                            Name = "Dining"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gas stations, ride-sharing, taxis, public transit, parking, tolls, and auto services",
                            Keywords = "gas,fuel,petro,shell,esso,ultramar,uber,lyft,taxi,transit,ttc,presto,stm,octranspo,translink,go transit,via rail,bus,parking,impark,407 etr,toll,car wash,jiffy lube,mr lube,kal tire",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Retail stores, online shopping, clothing, electronics, accessories, and department stores",
                            Keywords = "amazon,retail,store,clothing,electronics,mall,walmart,winners,marshalls,old navy,gap,h&m,zara,uniqlo,aritzia,lululemon,sport chek,best buy,staples,coach,michael kors,roots,indigo,chapters,ebay,etsy,wayfair,dollarama,canadian tire,nike,adidas,aldo,foot locker,simons",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Streaming services, movies, concerts, gaming, sports events, and recreational activities",
                            Keywords = "netflix,spotify,cinema,theatre,gaming,concert,ticket,disney,steam,crave,apple tv,youtube,prime video,dazn,cineplex,ticketmaster,stubhub,xbox,playstation,nintendo,epic games,audible,escape room,bowling,casino",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pharmacies, medical clinics, hospitals, gyms, fitness studios, dental, and vision care",
                            Keywords = "pharmacy,drugstore,doctor,hospital,clinic,gym,fitness,dental,vision,shoppers drug mart,rexall,pharmasave,lifelabs,dynacare,goodlife,anytime fitness,ymca,orangetheory,f45,physiotherapy,massage,optometrist,lenscrafters,clearly",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electricity, natural gas, water, internet, and cell phone providers",
                            Keywords = "hydro,electric,internet,phone,water,utility,rogers,bell,telus,fido,koodo,public mobile,shaw,videotron,eastlink,teksavvy,hydro one,toronto hydro,enbridge,fortis,bc hydro,hydro quebec,nova scotia power,atco",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flights, hotels, car rental, vacation packages, and travel booking platforms",
                            Keywords = "hotel,flight,airbnb,airline,car rental,vacation,resort,booking,expedia,air canada,westjet,porter,swoop,sunwing,air transat,marriott,hilton,hyatt,best western,enterprise,hertz,avis,priceline,hotels.com,kayak,trivago",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Banks, credit unions, insurance, investments, crypto, and money transfers",
                            Keywords = "bank,insurance,investment,loan,credit,brokerage,transfer,paypal,wealthsimple,questrade,coinbase,western union,manulife,sunlife,intact,belairdirect,aviva,desjardins,tangerine,simplii,eq bank,interac,stripe",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "University tuition, textbooks, online courses, and tutoring",
                            Keywords = "university,college,tuition,course,udemy,coursera,skillshare,books,school,learning,linkedin learning,pluralsight,masterclass,duolingo,chegg,campus store,bookstore,student",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Recurring software subscriptions, SaaS tools, and professional memberships",
                            Keywords = "subscription,membership,saas,annual fee,adobe,microsoft,google one,dropbox,icloud,notion,slack,zoom,1password,nordvpn,canva,github,openai,anthropic,grammarly,shopify,squarespace,mailchimp,hootsuite,figma,cursor",
                            Name = "Subscriptions"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rent, mortgage, furniture, appliances, hardware stores, and home improvement",
                            Keywords = "rent,mortgage,furniture,repair,hardware,ikea,home depot,rona,lowes,canadian tire home,leon's,the brick,sleep country,endy,casper,wayfair furniture,structube,article,restoration hardware,pottery barn,renovation,contractor,lease",
                            Name = "Home"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hair salons, barbershops, spas, cosmetics, and personal grooming",
                            Keywords = "salon,barber,spa,cosmetics,beauty,haircut,skincare,nails,sephora,mac cosmetics,lush,bath body works,the body shop,supercuts,great clips,sport clips,hand and stone,massage envy,ulta,morphe",
                            Name = "Personal Care"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Could not confidently classify",
                            Keywords = "",
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("BudgetingApp.Models.MerchantAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RawName")
                        .IsUnique();

                    b.ToTable("MerchantAlias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Transport",
                            RawName = "Uber"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Transport",
                            RawName = "Lyft"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dining",
                            RawName = "Uber Eats"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Dining",
                            RawName = "Doordash"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Dining",
                            RawName = "Skip The Dishes"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Shopping",
                            RawName = "Coach"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Shopping",
                            RawName = "Roots"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Shopping",
                            RawName = "Sail"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Shopping",
                            RawName = "Aldo"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Shopping",
                            RawName = "Simons"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Entertainment",
                            RawName = "Netflix"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Entertainment",
                            RawName = "Spotify"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Entertainment",
                            RawName = "Crave"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Entertainment",
                            RawName = "Dazn"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Utilities",
                            RawName = "Fido"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Utilities",
                            RawName = "Koodo"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Utilities",
                            RawName = "Shaw"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Utilities",
                            RawName = "Videotron"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Utilities",
                            RawName = "Teksavvy"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Finance",
                            RawName = "Wealthsimple"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Finance",
                            RawName = "Questrade"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Finance",
                            RawName = "Ndax"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Finance",
                            RawName = "Newton"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Subscriptions",
                            RawName = "Notion"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Subscriptions",
                            RawName = "Figma"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Subscriptions",
                            RawName = "Canva"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Subscriptions",
                            RawName = "Github"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Subscriptions",
                            RawName = "Openai"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Subscriptions",
                            RawName = "Anthropic"
                        });
                });

            modelBuilder.Entity("BudgetingApp.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetingApp.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BudgetingApp.Models.Transaction", b =>
                {
                    b.HasOne("BudgetingApp.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId");

                    b.HasOne("BudgetingApp.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetingApp.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetingApp.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
